# Lectures 1 & 2: Coding Single Neurons and Layers of Neurons
A neuron essentially takes in *n* inputs, and has *n* weights (as well as a bias term), and outputs:

${x_1}{w_1} + ... + {x_n}{w_n} + b$

In [1]:
# example neuron with three inputs
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2

outputs = (inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias)
outputs

2.3

These neurons can be chained together into a layer, with each input going to each neuron once, looking something like this: 

![](neuron_layer_diagram.png)

This nature plays very well into the mathematical concept of matrices, which is why the network weights are always represented as a $n * i$ matrix (where $n$ is the number of neurons and $i$ is the number of inputs), while the inputs are represented as a vector.

In [3]:
# implementing a layer of neurons
inputs = [1, 2, 3, 2.5]
weights = [
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]
biases = [2, 3, 0.5]

outputs = [
    # neuron 1
    inputs[0]*weights[0][0] +
    inputs[1]*weights[0][1] +
    inputs[2]*weights[0][2] +
    inputs[3]*weights[0][3] + biases[0],
    # neuron 2
    inputs[0]*weights[1][0] +
    inputs[1]*weights[1][1] +
    inputs[2]*weights[1][2] +
    inputs[3]*weights[1][3] + biases[1],
    # neuron 3
    inputs[0]*weights[2][0] +
    inputs[1]*weights[2][1] +
    inputs[2]*weights[2][2] +
    inputs[3]*weights[2][3] + biases[2],
]

outputs

[4.8, 1.21, 2.385]

In [4]:
# rewriting the layer using loops to reduce the amount of code
inputs = [1.1, 2.2, 3.3]
weights = [
    [2, 0, 0],
    [2, 2, 0],
    [2, 2, 2],
]
biases = [0, 0, 1]
outputs = []

for neuron_weights, neuron_bias in zip(weights, biases):
    output = 0
    for input, weight in zip(inputs, neuron_weights):
        output += input * weight
    output += neuron_bias
    outputs.append(output)

outputs

[2.2, 6.6000000000000005, 14.2]

Now, we can reduce the amount of code needed even further by using the NumPy Python library (specifically the `np.dot()` dot product operation)

The `np.dot()` command can be used in three instances (related to NNs):
- Vector x Vector -> Neuron
- Vector x Matrix -> Layer
- Matrix x Matrix -> Batch

In [7]:
# coding a neuron using NumPy
import numpy as np
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

# dot product between two vectors is commutative, so we can write it either way
outputs = np.dot(weights, inputs) + bias
print(outputs)
outputs = np.dot(inputs, weights) + bias
print(outputs)

4.8
4.8


In [3]:
# coding a layer using NumPy
inputs = np.array([1.0, 2.0, 3.0, 2.5])
weights = np.array([
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, 0.27, 0.17, 0.87],
])
biases = np.array([2.0, 3.0, 0.5])

outputs = np.dot(weights, inputs) + biases
print(outputs)
# since this is matrix vector multiplication, we can only switch the order of the elements if we transpose the weight matrix
outputs = np.dot(inputs, weights.T) + biases
print(outputs)

[4.8   1.21  3.465]
[4.8   1.21  3.465]


In [5]:
# coding a data batch using NumPy
inputs = np.array([
    [1, 2, 3, 2.5],
    [2, 5, -1, 2.0],
    [-1.5, 2.7, 3.3, -0.8],
])
weights = np.array([
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87],
])
biases = np.array([2.0, 3.0, 0.5])

outputs = np.dot(inputs, weights.T) + biases
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


Now the next step will be to chain these layers together

In [6]:
inputs = np.array([
    [1, 2, 3, 2.5],
    [2, 5, -1, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
])
weights = np.array([
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87],
])
biases = np.array([2.0, 3.0, 0.5])

weights2 = np.array([
    [0.1, -0.14, 0.5],
    [-0.5, 0.12, -0.33],
    [-0.44, 0.73, -0.13],
])
biases2 = np.array([-1, 2, -0.5])

layer1_out = np.dot(inputs, weights.T) + biases
layer2_out = np.dot(layer1_out, weights2.T) + biases2
layer2_out

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])